name = "downstream2"
uuid = "4a37de67-13e7-4c3e-bdb6-c307718e11fa"
authors = ["Aaron Peikert", "Maximilian S. Ernst"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
